_home:
    pattern:  /
    defaults: { _controller: XMBForumBundle:Home:index, forum: 0 }
    
_home_long:
    pattern: /home/{forum}
    defaults: { _controller: XMBForumBundle:Home:index, forum: 0 }    
    
_thread_new_all:
    pattern: /thread/new
    defaults: { _controller: XMBForumBundle:Thread:new }
    
_thread:
    pattern: /thread/{slug}
    defaults: { _controller: XMBForumBundle:Thread:index }    
    
_thread_new:
    pattern: /thread/new/{forum}
    defaults: { _controller: XMBForumBundle:Thread:new, forum: 0 }
    
_ajax:
    pattern: /ajax/{action}
    defaults: { _controller: XMBForumBundle:Ajax:index }

_profile_base:
    pattern: /profile
    defaults: { _controller: XMBForumBundle:Profile:index } 

_profile:
    pattern: /profile/{username}
    defaults: { _controller: XMBForumBundle:Profile:index }
    
_messages:
    pattern: /messages
    defaults: { _controller: XMBForumBundle:Messages:index }
    
_error:
    pattern: /error
    defaults: { _controller: XMBForumBundle:Error:index }
    
_install:
    pattern: /install
    defaults: { _controller: XMBForumBundle:Install:index }