parameters:


services:
    xmb.security.interactive_login_listener:
        class: XMB\ForumBundle\Listener\InteractiveLoginListener
        tags:
            - { name: kernel.security, event: security.interactive_login, method: onKernelException }
    
    forum_user.registration.form.type:
        class: XMB\ForumBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: forum_user_registration }
            
    twig.extension.xmb_global:
        class: XMB\ForumBundle\Globals\XMBGlobal
        arguments:
            doctrine: "@doctrine"
            container: "@service_container"
        tags:
            - { name: twig.extension }       
