_home:
    pattern:  /
    defaults: { _controller: TodoBundle:Default:index }
    
_profile:
    pattern: /profile
    defaults: { _controller: TodoBundle:Default:index }

_beta:
    pattern: /beta/{action}
    defaults: { _controller: TodoBundle:Beta:route, action: apply }
    
_beta_home:
    pattern: /beta
    defaults: { _controller: TodoBundle:Beta:index }